#!/usr/bin/env node
"use strict";
var libphonenumber = require('libphonenumber');
var readline = require('readline');
var pnf = {};
var numbers = [];

pnf.options = {
  format: 'e164',
  lang: 'FR'
}
pnf.format = function(number) {
  libphonenumber[this.options.format](
    number,
    this.options.lang,
    function(error, result) {
      if (error) {
        console.error(
          number + " is not a valid number"
        );
      }
      if (result) {
        console.log(result);
      }
    }
  )
}

process.argv.shift()
process.argv.shift()
process.argv.forEach(function(arg) {
  switch(true) {
    case arg == '-intl':
    case arg == '--intl':
    case arg == '-international':
    case arg == '--international':
      pnf.options.format = 'intl';
      break;
    case arg == '-e164':
    case arg == '--e164':
      pnf.options.format = 'e164';
      break;
    case arg.substr(0,6) == '-lang=':
    case arg.substr(0,7) == '--lang=':
      pnf.options.lang = arg.split('=')[1];
      break;
    default:
      numbers.push(arg);
      break;
  }
})

if (numbers.length === 0) {
  var rl = readline.createInterface({
    input: process.stdin,
    output: function() {}
  });

  rl.on('line', function(line) {
    pnf.format(line)
  })

  rl.on('end', function() {
    process.exit(0);
  });
} else {
  numbers.forEach(function(number) {
    pnf.format(number)
  })
}
